[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read-write", path = "./" }]
ffi = true

solc = "0.8.24"
evm_version = "prague"
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
  '@solady/=lib/solady/src'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options